name:
 Deploy
 Website
on:
push:
branches:
 ["main"]
permissions:
 contents:
 read
pages:
 write
id-token:
 write

jobs:
 deploy:
  runs
 on:
 ubuntu-latest

steps:
  name:
 Checkout
 Repository
  uses:
 actions/checkout@v3

  name:
 Upload
 Artifact
  uses:
 actions/upload-pages-artifact@v1

  name:
 Deploy
 to
 Github
 Pages
  uses:actions/deploy-pages@v1
